from typing import List, Dict


_POSTAL_DATA: List[Dict] = [
    # ── Madrid (Comunidad de Madrid) ──────────────────────────────────────────
    {"postal_code": "28001", "municipality": "Madrid", "province": "Madrid", "ccaa": "Comunidad de Madrid", "population_density": 5400, "region_type": "capital"},
    {"postal_code": "28002", "municipality": "Madrid", "province": "Madrid", "ccaa": "Comunidad de Madrid", "population_density": 5200, "region_type": "capital"},
    {"postal_code": "28010", "municipality": "Madrid", "province": "Madrid", "ccaa": "Comunidad de Madrid", "population_density": 5600, "region_type": "capital"},
    {"postal_code": "28013", "municipality": "Madrid", "province": "Madrid", "ccaa": "Comunidad de Madrid", "population_density": 5100, "region_type": "capital"},
    {"postal_code": "28020", "municipality": "Madrid", "province": "Madrid", "ccaa": "Comunidad de Madrid", "population_density": 5300, "region_type": "capital"},
    {"postal_code": "28030", "municipality": "Madrid", "province": "Madrid", "ccaa": "Comunidad de Madrid", "population_density": 5000, "region_type": "capital"},
    {"postal_code": "28040", "municipality": "Madrid", "province": "Madrid", "ccaa": "Comunidad de Madrid", "population_density": 4800, "region_type": "capital"},
    {"postal_code": "28050", "municipality": "Madrid", "province": "Madrid", "ccaa": "Comunidad de Madrid", "population_density": 4600, "region_type": "capital"},
    {"postal_code": "28060", "municipality": "Madrid", "province": "Madrid", "ccaa": "Comunidad de Madrid", "population_density": 4400, "region_type": "capital"},
    {"postal_code": "28080", "municipality": "Madrid", "province": "Madrid", "ccaa": "Comunidad de Madrid", "population_density": 4200, "region_type": "capital"},
    {"postal_code": "28100", "municipality": "Alcobendas", "province": "Madrid", "ccaa": "Comunidad de Madrid", "population_density": 3100, "region_type": "urban"},
    {"postal_code": "28200", "municipality": "San Lorenzo de El Escorial", "province": "Madrid", "ccaa": "Comunidad de Madrid", "population_density": 450, "region_type": "suburban"},
    {"postal_code": "28300", "municipality": "Aranjuez", "province": "Madrid", "ccaa": "Comunidad de Madrid", "population_density": 620, "region_type": "suburban"},
    {"postal_code": "28400", "municipality": "Collado Villalba", "province": "Madrid", "ccaa": "Comunidad de Madrid", "population_density": 1800, "region_type": "suburban"},
    {"postal_code": "28500", "municipality": "Arganda del Rey", "province": "Madrid", "ccaa": "Comunidad de Madrid", "population_density": 980, "region_type": "suburban"},
    {"postal_code": "28700", "municipality": "San Sebastián de los Reyes", "province": "Madrid", "ccaa": "Comunidad de Madrid", "population_density": 2400, "region_type": "urban"},
    {"postal_code": "28900", "municipality": "Getafe", "province": "Madrid", "ccaa": "Comunidad de Madrid", "population_density": 2900, "region_type": "urban"},
    {"postal_code": "28903", "municipality": "Getafe", "province": "Madrid", "ccaa": "Comunidad de Madrid", "population_density": 2700, "region_type": "urban"},

    # ── Barcelona (Cataluña) ──────────────────────────────────────────────────
    {"postal_code": "08001", "municipality": "Barcelona", "province": "Barcelona", "ccaa": "Cataluña", "population_density": 16000, "region_type": "capital"},
    {"postal_code": "08002", "municipality": "Barcelona", "province": "Barcelona", "ccaa": "Cataluña", "population_density": 15800, "region_type": "capital"},
    {"postal_code": "08010", "municipality": "Barcelona", "province": "Barcelona", "ccaa": "Cataluña", "population_density": 15600, "region_type": "capital"},
    {"postal_code": "08020", "municipality": "Barcelona", "province": "Barcelona", "ccaa": "Cataluña", "population_density": 14000, "region_type": "capital"},
    {"postal_code": "08030", "municipality": "Barcelona", "province": "Barcelona", "ccaa": "Cataluña", "population_density": 14800, "region_type": "capital"},
    {"postal_code": "08040", "municipality": "Barcelona", "province": "Barcelona", "ccaa": "Cataluña", "population_density": 13500, "region_type": "capital"},
    {"postal_code": "08050", "municipality": "Barcelona", "province": "Barcelona", "ccaa": "Cataluña", "population_density": 13200, "region_type": "capital"},
    {"postal_code": "08060", "municipality": "Barcelona", "province": "Barcelona", "ccaa": "Cataluña", "population_density": 12900, "region_type": "capital"},
    {"postal_code": "08080", "municipality": "Barcelona", "province": "Barcelona", "ccaa": "Cataluña", "population_density": 12500, "region_type": "capital"},
    {"postal_code": "08100", "municipality": "Mollet del Vallès", "province": "Barcelona", "ccaa": "Cataluña", "population_density": 4200, "region_type": "urban"},
    {"postal_code": "08200", "municipality": "Sabadell", "province": "Barcelona", "ccaa": "Cataluña", "population_density": 6100, "region_type": "urban"},
    {"postal_code": "08300", "municipality": "Mataró", "province": "Barcelona", "ccaa": "Cataluña", "population_density": 3800, "region_type": "urban"},
    {"postal_code": "08400", "municipality": "Granollers", "province": "Barcelona", "ccaa": "Cataluña", "population_density": 4500, "region_type": "urban"},
    {"postal_code": "08500", "municipality": "Vic", "province": "Barcelona", "ccaa": "Cataluña", "population_density": 1600, "region_type": "suburban"},
    {"postal_code": "08700", "municipality": "Igualada", "province": "Barcelona", "ccaa": "Cataluña", "population_density": 2100, "region_type": "suburban"},
    {"postal_code": "08800", "municipality": "Vilanova i la Geltrú", "province": "Barcelona", "ccaa": "Cataluña", "population_density": 2700, "region_type": "suburban"},
    {"postal_code": "08900", "municipality": "Hospitalet de Llobregat", "province": "Barcelona", "ccaa": "Cataluña", "population_density": 20000, "region_type": "urban"},
    {"postal_code": "08940", "municipality": "Cornellà de Llobregat", "province": "Barcelona", "ccaa": "Cataluña", "population_density": 9600, "region_type": "urban"},

    # ── Valencia (Comunitat Valenciana) ───────────────────────────────────────
    {"postal_code": "46001", "municipality": "Valencia", "province": "Valencia", "ccaa": "Comunitat Valenciana", "population_density": 5800, "region_type": "capital"},
    {"postal_code": "46002", "municipality": "Valencia", "province": "Valencia", "ccaa": "Comunitat Valenciana", "population_density": 5600, "region_type": "capital"},
    {"postal_code": "46010", "municipality": "Valencia", "province": "Valencia", "ccaa": "Comunitat Valenciana", "population_density": 5400, "region_type": "capital"},
    {"postal_code": "46020", "municipality": "Valencia", "province": "Valencia", "ccaa": "Comunitat Valenciana", "population_density": 5200, "region_type": "capital"},
    {"postal_code": "46025", "municipality": "Valencia", "province": "Valencia", "ccaa": "Comunitat Valenciana", "population_density": 4900, "region_type": "capital"},
    {"postal_code": "46100", "municipality": "Burjassot", "province": "Valencia", "ccaa": "Comunitat Valenciana", "population_density": 8200, "region_type": "urban"},
    {"postal_code": "46200", "municipality": "Paiporta", "province": "Valencia", "ccaa": "Comunitat Valenciana", "population_density": 4100, "region_type": "suburban"},
    {"postal_code": "46400", "municipality": "Cullera", "province": "Valencia", "ccaa": "Comunitat Valenciana", "population_density": 480, "region_type": "suburban"},
    {"postal_code": "46500", "municipality": "Sagunto", "province": "Valencia", "ccaa": "Comunitat Valenciana", "population_density": 370, "region_type": "suburban"},
    {"postal_code": "46600", "municipality": "Alzira", "province": "Valencia", "ccaa": "Comunitat Valenciana", "population_density": 590, "region_type": "suburban"},

    # ── Sevilla (Andalucía) ───────────────────────────────────────────────────
    {"postal_code": "41001", "municipality": "Sevilla", "province": "Sevilla", "ccaa": "Andalucía", "population_density": 4700, "region_type": "capital"},
    {"postal_code": "41002", "municipality": "Sevilla", "province": "Sevilla", "ccaa": "Andalucía", "population_density": 4600, "region_type": "capital"},
    {"postal_code": "41003", "municipality": "Sevilla", "province": "Sevilla", "ccaa": "Andalucía", "population_density": 4500, "region_type": "capital"},
    {"postal_code": "41010", "municipality": "Sevilla", "province": "Sevilla", "ccaa": "Andalucía", "population_density": 4300, "region_type": "capital"},
    {"postal_code": "41020", "municipality": "Sevilla", "province": "Sevilla", "ccaa": "Andalucía", "population_density": 4100, "region_type": "capital"},
    {"postal_code": "41100", "municipality": "Coria del Río", "province": "Sevilla", "ccaa": "Andalucía", "population_density": 550, "region_type": "suburban"},
    {"postal_code": "41200", "municipality": "Alcalá del Río", "province": "Sevilla", "ccaa": "Andalucía", "population_density": 310, "region_type": "suburban"},
    {"postal_code": "41400", "municipality": "Écija", "province": "Sevilla", "ccaa": "Andalucía", "population_density": 140, "region_type": "rural"},
    {"postal_code": "41500", "municipality": "Alcalá de Guadaíra", "province": "Sevilla", "ccaa": "Andalucía", "population_density": 860, "region_type": "suburban"},
    {"postal_code": "41700", "municipality": "Dos Hermanas", "province": "Sevilla", "ccaa": "Andalucía", "population_density": 1400, "region_type": "urban"},

    # ── Zaragoza (Aragón) ─────────────────────────────────────────────────────
    {"postal_code": "50001", "municipality": "Zaragoza", "province": "Zaragoza", "ccaa": "Aragón", "population_density": 2800, "region_type": "capital"},
    {"postal_code": "50002", "municipality": "Zaragoza", "province": "Zaragoza", "ccaa": "Aragón", "population_density": 2700, "region_type": "capital"},
    {"postal_code": "50010", "municipality": "Zaragoza", "province": "Zaragoza", "ccaa": "Aragón", "population_density": 2600, "region_type": "capital"},
    {"postal_code": "50018", "municipality": "Zaragoza", "province": "Zaragoza", "ccaa": "Aragón", "population_density": 2400, "region_type": "capital"},
    {"postal_code": "50100", "municipality": "La Almunia de Doña Godina", "province": "Zaragoza", "ccaa": "Aragón", "population_density": 220, "region_type": "rural"},
    {"postal_code": "50300", "municipality": "Calatayud", "province": "Zaragoza", "ccaa": "Aragón", "population_density": 290, "region_type": "suburban"},
    {"postal_code": "50500", "municipality": "Tarazona", "province": "Zaragoza", "ccaa": "Aragón", "population_density": 240, "region_type": "suburban"},
    {"postal_code": "50600", "municipality": "Ejea de los Caballeros", "province": "Zaragoza", "ccaa": "Aragón", "population_density": 120, "region_type": "rural"},
    {"postal_code": "22001", "municipality": "Huesca", "province": "Huesca", "ccaa": "Aragón", "population_density": 580, "region_type": "suburban"},
    {"postal_code": "44001", "municipality": "Teruel", "province": "Teruel", "ccaa": "Aragón", "population_density": 350, "region_type": "suburban"},

    # ── Bilbao (País Vasco) ───────────────────────────────────────────────────
    {"postal_code": "48001", "municipality": "Bilbao", "province": "Vizcaya", "ccaa": "País Vasco", "population_density": 8500, "region_type": "capital"},
    {"postal_code": "48002", "municipality": "Bilbao", "province": "Vizcaya", "ccaa": "País Vasco", "population_density": 8300, "region_type": "capital"},
    {"postal_code": "48003", "municipality": "Bilbao", "province": "Vizcaya", "ccaa": "País Vasco", "population_density": 8100, "region_type": "capital"},
    {"postal_code": "48010", "municipality": "Bilbao", "province": "Vizcaya", "ccaa": "País Vasco", "population_density": 7800, "region_type": "capital"},
    {"postal_code": "48015", "municipality": "Bilbao", "province": "Vizcaya", "ccaa": "País Vasco", "population_density": 7500, "region_type": "capital"},
    {"postal_code": "48100", "municipality": "Mungia", "province": "Vizcaya", "ccaa": "País Vasco", "population_density": 460, "region_type": "suburban"},
    {"postal_code": "48200", "municipality": "Durango", "province": "Vizcaya", "ccaa": "País Vasco", "population_density": 2800, "region_type": "urban"},
    {"postal_code": "48300", "municipality": "Gernika-Lumo", "province": "Vizcaya", "ccaa": "País Vasco", "population_density": 1200, "region_type": "suburban"},
    {"postal_code": "20001", "municipality": "San Sebastián", "province": "Guipúzcoa", "ccaa": "País Vasco", "population_density": 6400, "region_type": "capital"},
    {"postal_code": "20012", "municipality": "San Sebastián", "province": "Guipúzcoa", "ccaa": "País Vasco", "population_density": 5900, "region_type": "capital"},
    {"postal_code": "01001", "municipality": "Vitoria-Gasteiz", "province": "Álava", "ccaa": "País Vasco", "population_density": 2200, "region_type": "capital"},
    {"postal_code": "01010", "municipality": "Vitoria-Gasteiz", "province": "Álava", "ccaa": "País Vasco", "population_density": 2000, "region_type": "capital"},

    # ── Málaga (Andalucía) ────────────────────────────────────────────────────
    {"postal_code": "29001", "municipality": "Málaga", "province": "Málaga", "ccaa": "Andalucía", "population_density": 5200, "region_type": "capital"},
    {"postal_code": "29002", "municipality": "Málaga", "province": "Málaga", "ccaa": "Andalucía", "population_density": 5000, "region_type": "capital"},
    {"postal_code": "29006", "municipality": "Málaga", "province": "Málaga", "ccaa": "Andalucía", "population_density": 4800, "region_type": "capital"},
    {"postal_code": "29014", "municipality": "Málaga", "province": "Málaga", "ccaa": "Andalucía", "population_density": 4400, "region_type": "capital"},
    {"postal_code": "29400", "municipality": "Ronda", "province": "Málaga", "ccaa": "Andalucía", "population_density": 280, "region_type": "suburban"},
    {"postal_code": "29600", "municipality": "Marbella", "province": "Málaga", "ccaa": "Andalucía", "population_density": 820, "region_type": "urban"},
    {"postal_code": "29620", "municipality": "Torremolinos", "province": "Málaga", "ccaa": "Andalucía", "population_density": 3400, "region_type": "urban"},
    {"postal_code": "29630", "municipality": "Benalmádena", "province": "Málaga", "ccaa": "Andalucía", "population_density": 1900, "region_type": "suburban"},
    {"postal_code": "29700", "municipality": "Vélez-Málaga", "province": "Málaga", "ccaa": "Andalucía", "population_density": 420, "region_type": "suburban"},
    {"postal_code": "29730", "municipality": "Rincón de la Victoria", "province": "Málaga", "ccaa": "Andalucía", "population_density": 1100, "region_type": "suburban"},

    # ── Murcia (Región de Murcia) ─────────────────────────────────────────────
    {"postal_code": "30001", "municipality": "Murcia", "province": "Murcia", "ccaa": "Región de Murcia", "population_density": 1200, "region_type": "capital"},
    {"postal_code": "30002", "municipality": "Murcia", "province": "Murcia", "ccaa": "Región de Murcia", "population_density": 1100, "region_type": "capital"},
    {"postal_code": "30009", "municipality": "Murcia", "province": "Murcia", "ccaa": "Región de Murcia", "population_density": 1000, "region_type": "capital"},
    {"postal_code": "30100", "municipality": "Espinardo", "province": "Murcia", "ccaa": "Región de Murcia", "population_density": 620, "region_type": "suburban"},
    {"postal_code": "30200", "municipality": "Cartagena", "province": "Murcia", "ccaa": "Región de Murcia", "population_density": 760, "region_type": "urban"},
    {"postal_code": "30300", "municipality": "Caravaca de la Cruz", "province": "Murcia", "ccaa": "Región de Murcia", "population_density": 110, "region_type": "rural"},
    {"postal_code": "30500", "municipality": "Molina de Segura", "province": "Murcia", "ccaa": "Región de Murcia", "population_density": 930, "region_type": "suburban"},
    {"postal_code": "30600", "municipality": "Archena", "province": "Murcia", "ccaa": "Región de Murcia", "population_density": 570, "region_type": "suburban"},
    {"postal_code": "30700", "municipality": "Torre-Pacheco", "province": "Murcia", "ccaa": "Región de Murcia", "population_density": 190, "region_type": "rural"},
    {"postal_code": "30800", "municipality": "Lorca", "province": "Murcia", "ccaa": "Región de Murcia", "population_density": 95, "region_type": "rural"},

    # ── Valladolid (Castilla y León) ──────────────────────────────────────────
    {"postal_code": "47001", "municipality": "Valladolid", "province": "Valladolid", "ccaa": "Castilla y León", "population_density": 2400, "region_type": "capital"},
    {"postal_code": "47002", "municipality": "Valladolid", "province": "Valladolid", "ccaa": "Castilla y León", "population_density": 2300, "region_type": "capital"},
    {"postal_code": "47014", "municipality": "Valladolid", "province": "Valladolid", "ccaa": "Castilla y León", "population_density": 2100, "region_type": "capital"},
    {"postal_code": "47100", "municipality": "Tordesillas", "province": "Valladolid", "ccaa": "Castilla y León", "population_density": 190, "region_type": "rural"},
    {"postal_code": "47400", "municipality": "Medina del Campo", "province": "Valladolid", "ccaa": "Castilla y León", "population_density": 280, "region_type": "suburban"},
    {"postal_code": "37001", "municipality": "Salamanca", "province": "Salamanca", "ccaa": "Castilla y León", "population_density": 1800, "region_type": "capital"},
    {"postal_code": "37008", "municipality": "Salamanca", "province": "Salamanca", "ccaa": "Castilla y León", "population_density": 1700, "region_type": "capital"},
    {"postal_code": "09001", "municipality": "Burgos", "province": "Burgos", "ccaa": "Castilla y León", "population_density": 1500, "region_type": "capital"},
    {"postal_code": "24001", "municipality": "León", "province": "León", "ccaa": "Castilla y León", "population_density": 1400, "region_type": "capital"},
    {"postal_code": "34001", "municipality": "Palencia", "province": "Palencia", "ccaa": "Castilla y León", "population_density": 750, "region_type": "capital"},

    # ── Alicante (Comunitat Valenciana) ───────────────────────────────────────
    {"postal_code": "03001", "municipality": "Alicante", "province": "Alicante", "ccaa": "Comunitat Valenciana", "population_density": 3200, "region_type": "capital"},
    {"postal_code": "03002", "municipality": "Alicante", "province": "Alicante", "ccaa": "Comunitat Valenciana", "population_density": 3100, "region_type": "capital"},
    {"postal_code": "03010", "municipality": "Alicante", "province": "Alicante", "ccaa": "Comunitat Valenciana", "population_density": 3000, "region_type": "capital"},
    {"postal_code": "03016", "municipality": "Alicante", "province": "Alicante", "ccaa": "Comunitat Valenciana", "population_density": 2800, "region_type": "capital"},
    {"postal_code": "03100", "municipality": "Mutxamel", "province": "Alicante", "ccaa": "Comunitat Valenciana", "population_density": 610, "region_type": "suburban"},
    {"postal_code": "03200", "municipality": "Elche", "province": "Alicante", "ccaa": "Comunitat Valenciana", "population_density": 960, "region_type": "urban"},
    {"postal_code": "03300", "municipality": "Orihuela", "province": "Alicante", "ccaa": "Comunitat Valenciana", "population_density": 140, "region_type": "rural"},
    {"postal_code": "03400", "municipality": "Villena", "province": "Alicante", "ccaa": "Comunitat Valenciana", "population_density": 250, "region_type": "suburban"},
    {"postal_code": "03500", "municipality": "Benidorm", "province": "Alicante", "ccaa": "Comunitat Valenciana", "population_density": 2100, "region_type": "urban"},
    {"postal_code": "03600", "municipality": "Elda", "province": "Alicante", "ccaa": "Comunitat Valenciana", "population_density": 1800, "region_type": "urban"},

    # ── Otras ciudades y municipios menores ───────────────────────────────────
    {"postal_code": "15001", "municipality": "A Coruña", "province": "A Coruña", "ccaa": "Galicia", "population_density": 6200, "region_type": "capital"},
    {"postal_code": "15006", "municipality": "A Coruña", "province": "A Coruña", "ccaa": "Galicia", "population_density": 5900, "region_type": "capital"},
    {"postal_code": "15700", "municipality": "Santiago de Compostela", "province": "A Coruña", "ccaa": "Galicia", "population_density": 1400, "region_type": "capital"},
    {"postal_code": "36001", "municipality": "Pontevedra", "province": "Pontevedra", "ccaa": "Galicia", "population_density": 1100, "region_type": "capital"},
    {"postal_code": "36201", "municipality": "Vigo", "province": "Pontevedra", "ccaa": "Galicia", "population_density": 5600, "region_type": "capital"},
    {"postal_code": "36210", "municipality": "Vigo", "province": "Pontevedra", "ccaa": "Galicia", "population_density": 5200, "region_type": "capital"},
    {"postal_code": "32001", "municipality": "Ourense", "province": "Ourense", "ccaa": "Galicia", "population_density": 2300, "region_type": "capital"},
    {"postal_code": "27001", "municipality": "Lugo", "province": "Lugo", "ccaa": "Galicia", "population_density": 820, "region_type": "capital"},
    {"postal_code": "15100", "municipality": "Carballo", "province": "A Coruña", "ccaa": "Galicia", "population_density": 200, "region_type": "suburban"},
    {"postal_code": "15300", "municipality": "Betanzos", "province": "A Coruña", "ccaa": "Galicia", "population_density": 175, "region_type": "rural"},
    {"postal_code": "33001", "municipality": "Oviedo", "province": "Asturias", "ccaa": "Principado de Asturias", "population_density": 1900, "region_type": "capital"},
    {"postal_code": "33201", "municipality": "Gijón", "province": "Asturias", "ccaa": "Principado de Asturias", "population_density": 4400, "region_type": "capital"},
    {"postal_code": "33400", "municipality": "Avilés", "province": "Asturias", "ccaa": "Principado de Asturias", "population_density": 2900, "region_type": "urban"},
    {"postal_code": "33700", "municipality": "Luarca", "province": "Asturias", "ccaa": "Principado de Asturias", "population_density": 65, "region_type": "rural"},
    {"postal_code": "39001", "municipality": "Santander", "province": "Cantabria", "ccaa": "Cantabria", "population_density": 4600, "region_type": "capital"},
    {"postal_code": "39300", "municipality": "Torrelavega", "province": "Cantabria", "ccaa": "Cantabria", "population_density": 2800, "region_type": "urban"},
    {"postal_code": "39400", "municipality": "Los Corrales de Buelna", "province": "Cantabria", "ccaa": "Cantabria", "population_density": 380, "region_type": "suburban"},
    {"postal_code": "26001", "municipality": "Logroño", "province": "La Rioja", "ccaa": "La Rioja", "population_density": 2100, "region_type": "capital"},
    {"postal_code": "26200", "municipality": "Haro", "province": "La Rioja", "ccaa": "La Rioja", "population_density": 600, "region_type": "suburban"},
    {"postal_code": "26500", "municipality": "Calahorra", "province": "La Rioja", "ccaa": "La Rioja", "population_density": 760, "region_type": "suburban"},
    {"postal_code": "31001", "municipality": "Pamplona", "province": "Navarra", "ccaa": "Comunidad Foral de Navarra", "population_density": 4300, "region_type": "capital"},
    {"postal_code": "31010", "municipality": "Pamplona", "province": "Navarra", "ccaa": "Comunidad Foral de Navarra", "population_density": 4100, "region_type": "capital"},
    {"postal_code": "31300", "municipality": "Tafalla", "province": "Navarra", "ccaa": "Comunidad Foral de Navarra", "population_density": 450, "region_type": "suburban"},
    {"postal_code": "31500", "municipality": "Tudela", "province": "Navarra", "ccaa": "Comunidad Foral de Navarra", "population_density": 490, "region_type": "suburban"},
    {"postal_code": "02001", "municipality": "Albacete", "province": "Albacete", "ccaa": "Castilla-La Mancha", "population_density": 1300, "region_type": "capital"},
    {"postal_code": "02006", "municipality": "Albacete", "province": "Albacete", "ccaa": "Castilla-La Mancha", "population_density": 1200, "region_type": "capital"},
    {"postal_code": "13001", "municipality": "Ciudad Real", "province": "Ciudad Real", "ccaa": "Castilla-La Mancha", "population_density": 800, "region_type": "capital"},
    {"postal_code": "16001", "municipality": "Cuenca", "province": "Cuenca", "ccaa": "Castilla-La Mancha", "population_density": 310, "region_type": "capital"},
    {"postal_code": "19001", "municipality": "Guadalajara", "province": "Guadalajara", "ccaa": "Castilla-La Mancha", "population_density": 740, "region_type": "capital"},
    {"postal_code": "45001", "municipality": "Toledo", "province": "Toledo", "ccaa": "Castilla-La Mancha", "population_density": 1100, "region_type": "capital"},
    {"postal_code": "06001", "municipality": "Badajoz", "province": "Badajoz", "ccaa": "Extremadura", "population_density": 550, "region_type": "capital"},
    {"postal_code": "06800", "municipality": "Mérida", "province": "Badajoz", "ccaa": "Extremadura", "population_density": 290, "region_type": "capital"},
    {"postal_code": "10001", "municipality": "Cáceres", "province": "Cáceres", "ccaa": "Extremadura", "population_density": 185, "region_type": "capital"},
    {"postal_code": "11001", "municipality": "Cádiz", "province": "Cádiz", "ccaa": "Andalucía", "population_density": 8200, "region_type": "capital"},
    {"postal_code": "11201", "municipality": "Algeciras", "province": "Cádiz", "ccaa": "Andalucía", "population_density": 2400, "region_type": "urban"},
    {"postal_code": "11500", "municipality": "El Puerto de Santa María", "province": "Cádiz", "ccaa": "Andalucía", "population_density": 530, "region_type": "suburban"},
    {"postal_code": "14001", "municipality": "Córdoba", "province": "Córdoba", "ccaa": "Andalucía", "population_density": 2000, "region_type": "capital"},
    {"postal_code": "14900", "municipality": "Lucena", "province": "Córdoba", "ccaa": "Andalucía", "population_density": 410, "region_type": "suburban"},
    {"postal_code": "18001", "municipality": "Granada", "province": "Granada", "ccaa": "Andalucía", "population_density": 2700, "region_type": "capital"},
    {"postal_code": "18014", "municipality": "Granada", "province": "Granada", "ccaa": "Andalucía", "population_density": 2500, "region_type": "capital"},
    {"postal_code": "21001", "municipality": "Huelva", "province": "Huelva", "ccaa": "Andalucía", "population_density": 1700, "region_type": "capital"},
    {"postal_code": "23001", "municipality": "Jaén", "province": "Jaén", "ccaa": "Andalucía", "population_density": 1100, "region_type": "capital"},
    {"postal_code": "04001", "municipality": "Almería", "province": "Almería", "ccaa": "Andalucía", "population_density": 1800, "region_type": "capital"},
    {"postal_code": "07001", "municipality": "Palma", "province": "Islas Baleares", "ccaa": "Islas Baleares", "population_density": 3700, "region_type": "capital"},
    {"postal_code": "07010", "municipality": "Palma", "province": "Islas Baleares", "ccaa": "Islas Baleares", "population_density": 3500, "region_type": "capital"},
    {"postal_code": "07100", "municipality": "Sóller", "province": "Islas Baleares", "ccaa": "Islas Baleares", "population_density": 110, "region_type": "rural"},
    {"postal_code": "07800", "municipality": "Ibiza", "province": "Islas Baleares", "ccaa": "Islas Baleares", "population_density": 1200, "region_type": "urban"},
    {"postal_code": "35001", "municipality": "Las Palmas de Gran Canaria", "province": "Las Palmas", "ccaa": "Canarias", "population_density": 4900, "region_type": "capital"},
    {"postal_code": "35010", "municipality": "Las Palmas de Gran Canaria", "province": "Las Palmas", "ccaa": "Canarias", "population_density": 4600, "region_type": "capital"},
    {"postal_code": "35100", "municipality": "Maspalomas", "province": "Las Palmas", "ccaa": "Canarias", "population_density": 580, "region_type": "suburban"},
    {"postal_code": "38001", "municipality": "Santa Cruz de Tenerife", "province": "Santa Cruz de Tenerife", "ccaa": "Canarias", "population_density": 5100, "region_type": "capital"},
    {"postal_code": "38005", "municipality": "Santa Cruz de Tenerife", "province": "Santa Cruz de Tenerife", "ccaa": "Canarias", "population_density": 4800, "region_type": "capital"},
    {"postal_code": "38400", "municipality": "Puerto de la Cruz", "province": "Santa Cruz de Tenerife", "ccaa": "Canarias", "population_density": 3200, "region_type": "urban"},
    {"postal_code": "51001", "municipality": "Ceuta", "province": "Ceuta", "ccaa": "Ciudad Autónoma de Ceuta", "population_density": 4300, "region_type": "capital"},
    {"postal_code": "52001", "municipality": "Melilla", "province": "Melilla", "ccaa": "Ciudad Autónoma de Melilla", "population_density": 7800, "region_type": "capital"},
]


def get_postal_codes() -> List[Dict]:
    return [record.copy() for record in _POSTAL_DATA]
